import type { Board, Label, Member, Task } from "./types"

const members: Record<string, Member> = {
  m1: { id: "m1", name: "Анна Петрова", initials: "АП", role: "Продакт-лид" },
  m2: { id: "m2", name: "Марк Резников", initials: "МР", role: "Инженер" },
  m3: { id: "m3", name: "Лия Чен", initials: "ЛЧ", role: "Дизайнер" },
  m4: { id: "m4", name: "Даниил Ким", initials: "ДК", role: "Инженер" },
  m5: { id: "m5", name: "София Бауэр", initials: "СБ", role: "QA" },
  m6: { id: "m6", name: "Олег Хаддад", initials: "ОХ", role: "Инженер" },
}

const labels: Record<string, Label> = {
  l1: { id: "l1", name: "Фронтенд", color: "indigo" },
  l2: { id: "l2", name: "Бэкенд", color: "sky" },
  l3: { id: "l3", name: "Дизайн", color: "rose" },
  l4: { id: "l4", name: "Баг", color: "amber" },
  l5: { id: "l5", name: "Исследование", color: "emerald" },
  l6: { id: "l6", name: "Техдолг", color: "slate" },
}

const tasks: Record<string, Task> = {
  t1: {
    id: "t1",
    key: "FB-101",
    title: "Сценарий онбординга для новых воркспейсов",
    description:
      "Описать первый запуск: пустое состояние, демо-доска, шаг приглашения коллег.",
    columnId: "c1",
    priority: "high",
    labels: ["l3", "l5"],
    assigneeIds: ["m3", "m1"],
    dueDate: "2026-05-12",
    commentsCount: 4,
    attachmentsCount: 2,
    checklist: { total: 6, done: 2 },
    createdAt: "2026-04-18",
  },
  t2: {
    id: "t2",
    key: "FB-102",
    title: "Аудит цветовых токенов в дизайн-системе",
    columnId: "c1",
    priority: "medium",
    labels: ["l3", "l6"],
    assigneeIds: ["m3"],
    commentsCount: 1,
    attachmentsCount: 0,
    createdAt: "2026-04-19",
  },
  t3: {
    id: "t3",
    key: "FB-103",
    title: "Спайк: realtime-синхронизация через Postgres CDC",
    description:
      "Сравнить LISTEN/NOTIFY и логическую репликацию для ленты активности.",
    columnId: "c1",
    priority: "low",
    labels: ["l2", "l5"],
    assigneeIds: ["m2"],
    commentsCount: 0,
    attachmentsCount: 0,
    createdAt: "2026-04-20",
  },
  t4: {
    id: "t4",
    key: "FB-104",
    title: "Перетаскивание между колонками тормозит в Safari",
    description:
      "Воспроизводится на macOS 14, заметные подёргивания при переносе карточек между колонками.",
    columnId: "c2",
    priority: "urgent",
    labels: ["l4", "l1"],
    assigneeIds: ["m4", "m2"],
    dueDate: "2026-04-28",
    commentsCount: 7,
    attachmentsCount: 1,
    checklist: { total: 4, done: 3 },
    createdAt: "2026-04-15",
  },
  t5: {
    id: "t5",
    key: "FB-105",
    title: "Горячие клавиши: J/K, C, /, ?",
    columnId: "c2",
    priority: "medium",
    labels: ["l1"],
    assigneeIds: ["m6"],
    dueDate: "2026-05-02",
    commentsCount: 2,
    attachmentsCount: 0,
    checklist: { total: 8, done: 5 },
    createdAt: "2026-04-16",
  },
  t6: {
    id: "t6",
    key: "FB-106",
    title: "Фильтры по лейблам и приоритету в шапке доски",
    columnId: "c2",
    priority: "medium",
    labels: ["l1"],
    assigneeIds: ["m4"],
    commentsCount: 1,
    attachmentsCount: 0,
    createdAt: "2026-04-17",
  },
  t7: {
    id: "t7",
    key: "FB-107",
    title: "API: курсорная пагинация для журнала активности",
    columnId: "c3",
    priority: "high",
    labels: ["l2"],
    assigneeIds: ["m2", "m6"],
    dueDate: "2026-04-30",
    commentsCount: 3,
    attachmentsCount: 0,
    checklist: { total: 5, done: 5 },
    createdAt: "2026-04-12",
  },
  t8: {
    id: "t8",
    key: "FB-108",
    title: "Пустые состояния для досок без задач",
    columnId: "c3",
    priority: "low",
    labels: ["l3", "l1"],
    assigneeIds: ["m3"],
    commentsCount: 0,
    attachmentsCount: 1,
    createdAt: "2026-04-14",
  },
  t9: {
    id: "t9",
    key: "FB-109",
    title: "QA: регрессия настроек воркспейса",
    columnId: "c4",
    priority: "medium",
    labels: ["l4"],
    assigneeIds: ["m5"],
    commentsCount: 5,
    attachmentsCount: 0,
    checklist: { total: 12, done: 12 },
    createdAt: "2026-04-08",
  },
  t10: {
    id: "t10",
    key: "FB-110",
    title: "Релиз тёмных токенов v1",
    columnId: "c4",
    priority: "high",
    labels: ["l3", "l1"],
    assigneeIds: ["m3", "m4"],
    commentsCount: 2,
    attachmentsCount: 3,
    createdAt: "2026-04-05",
  },
  t11: {
    id: "t11",
    key: "FB-111",
    title: "Авторизация: ротация refresh-токенов",
    columnId: "c4",
    priority: "urgent",
    labels: ["l2"],
    assigneeIds: ["m2"],
    commentsCount: 8,
    attachmentsCount: 0,
    checklist: { total: 7, done: 7 },
    createdAt: "2026-04-02",
  },
}

export const mockBoard: Board = {
  id: "b1",
  name: "Flowboard Web",
  description: "Q2 спринт — онбординг, realtime и доводка дизайна",
  columns: [
    { id: "c1", title: "Бэклог", taskIds: ["t1", "t2", "t3"] },
    { id: "c2", title: "В работе", taskIds: ["t4", "t5", "t6"], limit: 5 },
    { id: "c3", title: "На ревью", taskIds: ["t7", "t8"] },
    { id: "c4", title: "Готово", taskIds: ["t9", "t10", "t11"] },
  ],
  tasks,
  labels,
  members,
}

export const mockProjects = [
  { id: "b1", name: "Flowboard Web", emoji: "FW", color: "indigo" as const, active: true },
  { id: "b2", name: "Мобильное приложение", emoji: "МП", color: "emerald" as const },
  { id: "b3", name: "Маркетинг-сайт", emoji: "МС", color: "amber" as const },
  { id: "b4", name: "Внутренние инструменты", emoji: "ВИ", color: "sky" as const },
]
